repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        description: Format Rust code according to style guidelines.
        language: rust
        files: \.rs$
        pass_filenames: false
        entry: cargo fmt
        args: ["--all"]
      - id: cargo-clippy
        name: cargo clippy
        description: Catch common mistakes and improve Rust code with a collection of lints.
        language: rust
        files: (Cargo.(toml|lock)|\.rs$)
        pass_filenames: false
        entry: cargo clippy
        args: ["--workspace"]
      - id: cargo-check
        name: cargo check
        description: Check Rust code for compilation errors.
        language: rust
        files: (Cargo.(toml|lock)|\.rs$)
        pass_filenames: false
        entry: cargo check
        args: ["--workspace"]
